### ISSUE TITLE
Can't use beaglebone-black-just-copy-boot-to-eMMC.sh after doing a NetInstall

### ISSUE THREAD

**Issue by andrewlear23** [RobertCNelson/tools#5]
Just done a NetInstall of Debian 7.8 onto a BeagleBoneBlack, works great. However I'd now like to get the bootloader onto the eMMC. I've used this approach in the past, can't remember when but certainly last year.

Anyway I've copied down the beaglebone-black-just-copy-boot-to-eMMC.sh onto my BeagleBone .. but I get the message

"Error: script halting, system unrecognized...
unable to find: [/boot/uboot/uEnv.txt] is /dev/mmcblk0p1 mounted?"

Attached is a screenshot of my filesystem .. it's clear that mmcblk0p1 is my boot device. However sure enough /boot/uboot/uEnv.txt is missing.

![beaglebone_black_debian_install](https://cloud.githubusercontent.com/assets/8641227/5847208/9045ca10-a1c2-11e4-807f-468326d5d8dc.PNG)

I'm guessing that perhaps you've changed the way NetInstall / uboot works, however this script is still thinking the old way?

I tried the script beaglebone-black-copy-microSD-to-eMMC.sh  .. this gives the same sort of error.

Hoping you can help, because it's not the best having to hold down that fiddly S2 button each time.

Thanks

Andrew

**Comment by RobertCNelson** [comment]
Sorry, the scripts in this repo have kept up with the current bootloader setup:

http://elinux.org/Beagleboard:U-boot_partitioning_layout_2.0

In your case, just clear out the boot loader in eMMC:

```
sudo dd if=/dev/zero of=/dev/mmcblk1 bs=1M count=10
```
Regards,

**Comment by andrewlear23** [comment]
Thanks Robert, that worked and now the BeagleBone Black boots straight off the MicroSD without me having to hold down S2. Sorry if I'm being a pain here, but what would I need to do do if I wanted to copy my new Debian 7.7 install off the MicroSD and back on the eMMC, and have the BeagleBone Black boot without the MicroSD being present?

I have just tried the script beaglebone-black-copy-microSD-to-eMMC.sh   , but that still gives me the 
unable to find: [/boot/uboot/uEnv.txt] is /dev/mmcblk0p1 mounted?"

Again apologies if I'm a being a pain, it's just I'm new to all this. I'd also just like to say thanks for your excellent work your doing, much appreciated.

**Comment by RobertCNelson** [comment]
So, this script 'should' work:

https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/bbb-eMMC-flasher-eewiki-ext4.sh

```
wget https://raw.githubusercontent.com/RobertCNelson/boot-scripts/master/tools/eMMC/bbb-eMMC-flasher-eewiki-ext4.sh
chmod +x bbb-eMMC-flasher-eewiki-ext4.sh
sudo /bin/bash ./bbb-eMMC-flasher-eewiki-ext4.sh
```

However the problem with the "NetInstall" is the trampoline partition (boot partition that was used to load the NetInstaller...) It should work around it..  Totally untested...

Regards,

**Comment by andrewlear23** [comment]
Works great. I just had to install rsync since the script uses it. Apart from that I now have a BeagleBon Black that boot into Debian without a MicroSD being inserted.

Thanks again Robert
