### ISSUE TITLE
Write MLO, uboot.img, uImage,am335x-boneblack, rootfs on to eMMC/NAND on beaglebone black

### ISSUE THREAD

**Issue by ngoc233** [RobertCNelson/tools#7]
Hi I'm a newbie of embeded linux.  I'm following this tutorial https://embedjournal.com/kernel-compilation-beaglebone-black/  for boot make a custom linux . I have MLO, uboot.img, uImage,am335x-boneblack on the BOOT folder , and  bin, dev, home ,lost+found, mnt, run, sys, usr ,boot, etc, lib, media, proc, sbin, tmp ,var on RFS folder

I can boot my linux on beaglebone black with sdcard. So now I want to boot the linux with eMMC flash 

Sorry my English is not good. Does anybody have any idea of what did I do wrong or did I miss something?

**Comment by RobertCNelson** [comment]
@ngoc233 looking at my https://embedjournal.com/kernel-compilation-beaglebone-black/ my directions for moving the data from microSD to eMMC is not compatible as they assume a different partition setup.

Feel free to either follow my guide:

https://www.digikey.com/eewiki/display/linuxonarm/BeagleBone+Black

Closing this Issue for now, but feel free to re-open if you have any questions directly related to one of my eewiki or elinux guides on install debian/ubuntu to the BBB.

Regards,
